name: pre-commit

on:
  pull_request:
    branches:
      - "main"

jobs:
  pre-commit:
    # changing the following value will significantly affect github's billing. Be careful and consult with the team before changing it.
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup backend
        id: setup
        uses: ./.github/actions/setup

      - name: Setup-pre-commit
        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/uv
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('\.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv run --frozen pre-commit run --show-diff-on-failure --color=always --all-files --source ${{ github.event.pull_request.base.sha }} --origin ${{ github.event.pull_request.head.sha }} --show-diff-on-failure --color=always
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v5
        # Always commit changes even if pre-commit failed
        if: always()
        with:
          commit_message: "Automated pre-commit update"
